//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKiemKe
    {
        public string MaPKK { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SLHeThong { get; set; }
        public Nullable<int> SLThucTe { get; set; }
        public Nullable<int> SLLech { get; set; }
        public string LyDo { get; set; }
    
        public virtual PhieuKiemKe PhieuKiemKe { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
