//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuXuat()
        {
            this.ChiTietPXes = new HashSet<ChiTietPX>();
        }
    
        public string MaPX { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string MaDL { get; set; }
        public string MaNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPX> ChiTietPXes { get; set; }
        public virtual DaiLy DaiLy { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
