//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_KHOEntities3 : DbContext
    {
        public QL_KHOEntities3()
            : base("name=QL_KHOEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietKiemKe> ChiTietKiemKes { get; set; }
        public virtual DbSet<ChiTietPN> ChiTietPNs { get; set; }
        public virtual DbSet<ChiTietPX> ChiTietPXes { get; set; }
        public virtual DbSet<DaiLy> DaiLies { get; set; }
        public virtual DbSet<KhoHang> KhoHangs { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuKiemKe> PhieuKiemKes { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<PhieuXuat> PhieuXuats { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<vw_BaoCaoXuatNhapTon> vw_BaoCaoXuatNhapTon { get; set; }
        public virtual DbSet<vw_ChiTietPhieuNhap> vw_ChiTietPhieuNhap { get; set; }
        public virtual DbSet<vw_ChiTietPhieuXuat> vw_ChiTietPhieuXuat { get; set; }
        public virtual DbSet<vw_NhaCungCapTheoSanPham> vw_NhaCungCapTheoSanPham { get; set; }
        public virtual DbSet<vw_ThongTinSanPham> vw_ThongTinSanPham { get; set; }
    
        [DbFunction("QL_KHOEntities3", "fn_LichSuGiaoDichNhanVien")]
        public virtual IQueryable<fn_LichSuGiaoDichNhanVien_Result> fn_LichSuGiaoDichNhanVien(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_LichSuGiaoDichNhanVien_Result>("[QL_KHOEntities3].[fn_LichSuGiaoDichNhanVien](@MaNV)", maNVParameter);
        }
    
        [DbFunction("QL_KHOEntities3", "fn_PhieuNhapTheoKhoangThoiGian")]
        public virtual IQueryable<fn_PhieuNhapTheoKhoangThoiGian_Result> fn_PhieuNhapTheoKhoangThoiGian(Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc)
        {
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_PhieuNhapTheoKhoangThoiGian_Result>("[QL_KHOEntities3].[fn_PhieuNhapTheoKhoangThoiGian](@NgayBatDau, @NgayKetThuc)", ngayBatDauParameter, ngayKetThucParameter);
        }
    
        [DbFunction("QL_KHOEntities3", "fn_ThongKeSanPhamTheoLoai")]
        public virtual IQueryable<fn_ThongKeSanPhamTheoLoai_Result> fn_ThongKeSanPhamTheoLoai(string maLoai)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ThongKeSanPhamTheoLoai_Result>("[QL_KHOEntities3].[fn_ThongKeSanPhamTheoLoai](@MaLoai)", maLoaiParameter);
        }
    
        public virtual int sp_BaoCaoGiaTriTonKhoTheoLoai_Cursor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BaoCaoGiaTriTonKhoTheoLoai_Cursor");
        }
    
        public virtual int sp_GiaoTac_ThemChiTietPhieuXuat(string maPX, string maSP, Nullable<int> soLuong, Nullable<decimal> donGiaXuat)
        {
            var maPXParameter = maPX != null ?
                new ObjectParameter("MaPX", maPX) :
                new ObjectParameter("MaPX", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donGiaXuatParameter = donGiaXuat.HasValue ?
                new ObjectParameter("DonGiaXuat", donGiaXuat) :
                new ObjectParameter("DonGiaXuat", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GiaoTac_ThemChiTietPhieuXuat", maPXParameter, maSPParameter, soLuongParameter, donGiaXuatParameter);
        }
    
        public virtual ObjectResult<sp_GiaoTac_XemTonKhoAnToan_Result> sp_GiaoTac_XemTonKhoAnToan(string maSP)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GiaoTac_XemTonKhoAnToan_Result>("sp_GiaoTac_XemTonKhoAnToan", maSPParameter);
        }
    
        public virtual int sp_GiaoTac_XoaPhieuNhap(string maPN)
        {
            var maPNParameter = maPN != null ?
                new ObjectParameter("MaPN", maPN) :
                new ObjectParameter("MaPN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GiaoTac_XoaPhieuNhap", maPNParameter);
        }
    
        public virtual int sp_GiaoTac_XoaPhieuXuat(string maPX)
        {
            var maPXParameter = maPX != null ?
                new ObjectParameter("MaPX", maPX) :
                new ObjectParameter("MaPX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GiaoTac_XoaPhieuXuat", maPXParameter);
        }
    
        public virtual int sp_InsertChiTietPX(string maPX, string maSP, Nullable<int> soLuong, Nullable<decimal> donGiaXuat)
        {
            var maPXParameter = maPX != null ?
                new ObjectParameter("MaPX", maPX) :
                new ObjectParameter("MaPX", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donGiaXuatParameter = donGiaXuat.HasValue ?
                new ObjectParameter("DonGiaXuat", donGiaXuat) :
                new ObjectParameter("DonGiaXuat", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertChiTietPX", maPXParameter, maSPParameter, soLuongParameter, donGiaXuatParameter);
        }
    
        public virtual int sp_LayTongTienPhieuNhap(string manv, string mancc, string mapn, ObjectParameter tongtien)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            var mapnParameter = mapn != null ?
                new ObjectParameter("mapn", mapn) :
                new ObjectParameter("mapn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LayTongTienPhieuNhap", manvParameter, manccParameter, mapnParameter, tongtien);
        }
    
        public virtual int sp_TinhTienThuong(Nullable<decimal> luongCoBan, Nullable<double> heSo, ObjectParameter tienThuong)
        {
            var luongCoBanParameter = luongCoBan.HasValue ?
                new ObjectParameter("LuongCoBan", luongCoBan) :
                new ObjectParameter("LuongCoBan", typeof(decimal));
    
            var heSoParameter = heSo.HasValue ?
                new ObjectParameter("HeSo", heSo) :
                new ObjectParameter("HeSo", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TinhTienThuong", luongCoBanParameter, heSoParameter, tienThuong);
        }
    
        public virtual ObjectResult<sp_TongSoLuongSanPhamTheoPhieuXuat_Result> sp_TongSoLuongSanPhamTheoPhieuXuat(string mapx)
        {
            var mapxParameter = mapx != null ?
                new ObjectParameter("mapx", mapx) :
                new ObjectParameter("mapx", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TongSoLuongSanPhamTheoPhieuXuat_Result>("sp_TongSoLuongSanPhamTheoPhieuXuat", mapxParameter);
        }
    
        public virtual int sp_TongTonKhoTheoLoai(string maLoai, ObjectParameter tongSoLuong)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TongTonKhoTheoLoai", maLoaiParameter, tongSoLuong);
        }
    
        public virtual int sp_UpdateNhaCungCap(string maNCC, string tenNCC, string sDT, string diaChi, string email)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var tenNCCParameter = tenNCC != null ?
                new ObjectParameter("TenNCC", tenNCC) :
                new ObjectParameter("TenNCC", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateNhaCungCap", maNCCParameter, tenNCCParameter, sDTParameter, diaChiParameter, emailParameter);
        }
    
        public virtual int sp_XetThuongNhanVienXuatKho_Cursor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XetThuongNhanVienXuatKho_Cursor");
        }
    }
}
