//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ChiTietPhieuXuat
    {
        public string MaPX { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public string TenNhanVien { get; set; }
        public string TenDaiLy { get; set; }
        public string DiaChiDaiLy { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGiaXuat { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    }
}
