//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NhaCungCapTheoSanPham
    {
        public string Mã_Sản_Phẩm { get; set; }
        public string Tên_Sản_Phẩm { get; set; }
        public Nullable<int> Số_Lượng_Tồn { get; set; }
        public string Tên_Nhà_Cung_Cấp { get; set; }
        public string Số_Điện_Thoại_NCC { get; set; }
        public string Địa_Chỉ { get; set; }
    }
}
