//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ThongTinSanPham
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string TenLoai { get; set; }
        public string DVT { get; set; }
        public Nullable<int> SLTon { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> TongGiaTriTien { get; set; }
    }
}
